# docker-compose.yml
version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # Map port 80 in the container to port 3000 on the host
    environment:
      - NODE_ENV=production
